<template>
    <div id="app">
        <div style="display: flex; justify-content: center;">
            <div style="width: 600px;border: 1px solid black;">
                <div>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                </div>
                <ow-sticky :offset-top="100">
                    <div style="border: 1px solid red;">
                        Sticky
                        <img src="https://avatars1.githubusercontent.com/u/32581037?s=64&v=4" alt="">
                    </div>
                </ow-sticky>
                <div>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                    <p>Text1</p>
                    <p>Text2</p>
                    <p>Text3</p>
                    <p>Text4</p>
                    <p>Text5</p>
                    <p>Text6</p>
                    <p>Text7</p>
                    <p>Text8</p>
                    <p>Text9</p>
                    <p>Text10</p>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        name: 'app',
        data() {
            return {
            }
        },
        methods: {
        }
    }
</script>

<style lang="scss">
    #app {
        border: 1px solid;
        padding: 10px 15px;
        background: #ffaabb;
    }
</style>
